"" Vimrc By Mehran Zolghadr

"" General Settings
""runtime! archlinux.vim
:set number
:set ls=2
:set expandtab
:set t_Co=256 
"":set term=screen-256color
:set nowrap
set backspace=2 " make backspace work like most other programs
:set cursorline

:colorscheme solarized 
:set background=dark
:set nocp
:set clipboard=unnamed
:set clipboard=unnamedplus
:set ai
:set si
:set cindent
:syntax enable
:set showmatch
:set nohlsearch
:set pastetoggle=<F2>
:noremap <silent> #3 :tabprevious<CR> "" switch to previous tab with F3
:noremap <silent> #4 :tabnext<CR> "" switch to next tab with F2
:map <F8> :setlocal spell! spelllang=en_us<CR> "" check spelling with F8
:set splitright
:set splitbelow
:set mouse=a ""mouse intergration
"":set ignorecase ""ignore case in search


"" auto complete

:inoremap        (  ()<Left>
:inoremap        "  ""<Left>
:inoremap        `  ``<Left>
:inoremap        '  ''<Left>
:inoremap        [  []<Left>
:inoremap      {  {}<Left>


"" auto comment and uncomment with f6 and f7

:autocmd FileType c,cpp,java,scala,php let b:comment_leader = '// '
:autocmd FileType sh,ruby,python   let b:comment_leader = '# '
:noremap <silent> #6 :<C-B>silent <C-E>s/^/<C-R>=escape(b:comment_leader,'\/')<CR>/<CR>:nohlsearch<CR> "" commenting line with F6
:noremap <silent> #7 :<C-B>silent <C-E>s/^\V<C-R>=escape(b:comment_leader,'\/')<CR>//e<CR>:nohlsearch<CR> "" uncommenting line with F7

"" move between windows with alt and arrow keys
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>


"" execute

"":noremap <silent> #5 :!xfce4-terminal -hold -e './%' <CR> <CR> "" execute bash & python script with f5 for xfce terminal
:noremap <silent> #5 :!xfce4-terminal --hold -e 'python3 ./%' <CR> <CR>" execute python script with F5

"" plugins

"" plugin manager vim-plug settings
call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
Plug 'othree/html5.vim' 
Plug 'StanAngeloff/php.vim'
Plug 'Yggdroot/indentLine'
Plug 'davidhalter/jedi-vim'
Plug 'tpope/vim-surround'
Plug 'pangloss/vim-javascript'
Plug 'vim-syntastic/syntastic'
Plug 'vim-scripts/AutoComplPop'
Plug 'vim-scripts/L9'

call plug#end()

"" airline plugin setting
:let g:airline_theme='solarized' " set airline plugin theme
:let g:airline#extensions#tabline#enabled = 1 " showing tabs 
:let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
  endif

 " unicode symbols
  let g:airline_left_sep = '»'
  let g:airline_left_sep = '▶'
  let g:airline_right_sep = '«'
  let g:airline_right_sep = '◀'

" NERDTree plugin setting

"toggle showing NERDTree with F9
:map <F9> :NERDTreeToggle<CR> 

"open a NERDTree automatically when vim starts up if no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

"" open file vertically with ctrl + v 
let NERDTreeMapOpenVSplit='<c-v>'
"" Open file horizintally with ctrl + h
let NERDTreeMapOpenSplit='<c-h>'

" Open file in new tab with ctrl + t
:let NERDTreeMapOpenInTab='<c-t>'

"" indentline settings
let g:indentLine_color_term = 239
:let g:indentLine_char = '│'

"" autocomplpop settings
:set omnifunc=syntaxcomplete " This is necessary for acp plugin
:let g:acp_behaviorKeywordLength = 1 "  Length of keyword characters before the cursor, which are needed to attempt keyword completion

"" jedi not show preview
autocmd FileType python setlocal completeopt-=preview

"" end plugins settings


"hi CursorLine term=bold cterm=bold guibg=Grey40 
